baseURL = "https://crystalkimm.github.io/"
languageCode = "en-us"
title = "My Blog"
theme = "ananke"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
favicon = ""
site_logo = ""
description = "Digital Humanities Project 2020"
facebook = ""
instagram = ""
twitter = ""
youtube = ""
gitlab = ""
linkedin = ""
mastodon = ""
slack = ""
stackoverflow = ""
rss = ""
# choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
featured_image = "/images/background.jpg" #"/images/gohugo-default-sample-hero-image.jpg"
recent_posts_number = 2


[[menu.main]] # here are the buttons on the menu
identifier = "home"
name = "Home" # Button will display as "Home"
pre = "<br />"
url = "/"
weight = 100 # the weight decides the position of the button (higher or lower)

[[menu.main]]
identifier = "about" # this button will refer to a markdown file named "contact" in the content folder
name = "ABOUT"
pre = "<br />"
url = "/about"
weight = 0

[[menu.main]]
identifier = "blog" # this page will refer to a markdown file named "blog" in the content folder
name = "Blog"
pre = "<br />"
url = "/posts"
weight = 40
