baseURL = "https://crystalkimm.github.io/"
languageCode = "en-us"
title = "crystal's thoughts"
theme = "ananke"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
favicon = ""
site_logo = ""
description = "Digital Humanities Project 2020, current events and media consumption"
facebook = ""
instagram = ""
twitter = ""
youtube = ""
gitlab = ""
linkedin = ""
mastodon = ""
slack = ""
stackoverflow = ""
rss = ""
# choose a color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
featured_image = "/images/background.jpg" #"/images/gohugo-default-sample-hero-image.jpg"
recent_posts_number = 2


[[menu.main]] # here are the buttons on the menu
identifier = "home"
name = "HOME" # Button will display as "HOME"
pre = "<br />"
url = "/"
weight = -3 # the weight decides the position of the button (higher or lower)

[[menu.main]]
identifier = "about" # this button will refer to a markdown file named "contact" in the content folder
name = "ABOUT"
pre = "<br />"
url = "/about"
weight = -1

[[menu.main]]
identifier = "blog" # this page will refer to a markdown file named "blog" in the content folder
name = "BLOG"
pre = "<br />"
url = "/posts"
weight = -2
